// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/graph.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DependencyKind int32

const (
	DependencyKind_PACKAGE DependencyKind = 0
	DependencyKind_CONFIG  DependencyKind = 1
)

// Enum value maps for DependencyKind.
var (
	DependencyKind_name = map[int32]string{
		0: "PACKAGE",
		1: "CONFIG",
	}
	DependencyKind_value = map[string]int32{
		"PACKAGE": 0,
		"CONFIG":  1,
	}
)

func (x DependencyKind) Enum() *DependencyKind {
	p := new(DependencyKind)
	*p = x
	return p
}

func (x DependencyKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DependencyKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_graph_proto_enumTypes[0].Descriptor()
}

func (DependencyKind) Type() protoreflect.EnumType {
	return &file_proto_graph_proto_enumTypes[0]
}

func (x DependencyKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DependencyKind.Descriptor instead.
func (DependencyKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_graph_proto_rawDescGZIP(), []int{0}
}

type Dependency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Kind          DependencyKind         `protobuf:"varint,2,opt,name=kind,proto3,enum=graph.DependencyKind" json:"kind,omitempty"`
	Condition     string                 `protobuf:"bytes,3,opt,name=condition,proto3" json:"condition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dependency) Reset() {
	*x = Dependency{}
	mi := &file_proto_graph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dependency) ProtoMessage() {}

func (x *Dependency) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dependency.ProtoReflect.Descriptor instead.
func (*Dependency) Descriptor() ([]byte, []int) {
	return file_proto_graph_proto_rawDescGZIP(), []int{0}
}

func (x *Dependency) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Dependency) GetKind() DependencyKind {
	if x != nil {
		return x.Kind
	}
	return DependencyKind_PACKAGE
}

func (x *Dependency) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

type Package struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path             string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Depends          []*Dependency          `protobuf:"bytes,3,rep,name=depends,proto3" json:"depends,omitempty"`
	BuildDepends     []*Dependency          `protobuf:"bytes,4,rep,name=build_depends,json=buildDepends,proto3" json:"build_depends,omitempty"`
	HostBuildDepends []*Dependency          `protobuf:"bytes,5,rep,name=host_build_depends,json=hostBuildDepends,proto3" json:"host_build_depends,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Package) Reset() {
	*x = Package{}
	mi := &file_proto_graph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Package) ProtoMessage() {}

func (x *Package) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Package.ProtoReflect.Descriptor instead.
func (*Package) Descriptor() ([]byte, []int) {
	return file_proto_graph_proto_rawDescGZIP(), []int{1}
}

func (x *Package) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Package) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Package) GetDepends() []*Dependency {
	if x != nil {
		return x.Depends
	}
	return nil
}

func (x *Package) GetBuildDepends() []*Dependency {
	if x != nil {
		return x.BuildDepends
	}
	return nil
}

func (x *Package) GetHostBuildDepends() []*Dependency {
	if x != nil {
		return x.HostBuildDepends
	}
	return nil
}

type Graph struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packages      []*Package             `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Graph) Reset() {
	*x = Graph{}
	mi := &file_proto_graph_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Graph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Graph) ProtoMessage() {}

func (x *Graph) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Graph.ProtoReflect.Descriptor instead.
func (*Graph) Descriptor() ([]byte, []int) {
	return file_proto_graph_proto_rawDescGZIP(), []int{2}
}

func (x *Graph) GetPackages() []*Package {
	if x != nil {
		return x.Packages
	}
	return nil
}

var File_proto_graph_proto protoreflect.FileDescriptor

const file_proto_graph_proto_rawDesc = "" +
	"\n" +
	"\x11proto/graph.proto\x12\x05graph\"m\n" +
	"\n" +
	"Dependency\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12)\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x15.graph.DependencyKindR\x04kind\x12\x1c\n" +
	"\tcondition\x18\x03 \x01(\tR\tcondition\"\xd7\x01\n" +
	"\aPackage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12+\n" +
	"\adepends\x18\x03 \x03(\v2\x11.graph.DependencyR\adepends\x126\n" +
	"\rbuild_depends\x18\x04 \x03(\v2\x11.graph.DependencyR\fbuildDepends\x12?\n" +
	"\x12host_build_depends\x18\x05 \x03(\v2\x11.graph.DependencyR\x10hostBuildDepends\"3\n" +
	"\x05Graph\x12*\n" +
	"\bpackages\x18\x01 \x03(\v2\x0e.graph.PackageR\bpackages*)\n" +
	"\x0eDependencyKind\x12\v\n" +
	"\aPACKAGE\x10\x00\x12\n" +
	"\n" +
	"\x06CONFIG\x10\x01B\x1bZ\x19owlm/internal/proto;protob\x06proto3"

var (
	file_proto_graph_proto_rawDescOnce sync.Once
	file_proto_graph_proto_rawDescData []byte
)

func file_proto_graph_proto_rawDescGZIP() []byte {
	file_proto_graph_proto_rawDescOnce.Do(func() {
		file_proto_graph_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_graph_proto_rawDesc), len(file_proto_graph_proto_rawDesc)))
	})
	return file_proto_graph_proto_rawDescData
}

var file_proto_graph_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_graph_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_graph_proto_goTypes = []any{
	(DependencyKind)(0), // 0: graph.DependencyKind
	(*Dependency)(nil),  // 1: graph.Dependency
	(*Package)(nil),     // 2: graph.Package
	(*Graph)(nil),       // 3: graph.Graph
}
var file_proto_graph_proto_depIdxs = []int32{
	0, // 0: graph.Dependency.kind:type_name -> graph.DependencyKind
	1, // 1: graph.Package.depends:type_name -> graph.Dependency
	1, // 2: graph.Package.build_depends:type_name -> graph.Dependency
	1, // 3: graph.Package.host_build_depends:type_name -> graph.Dependency
	2, // 4: graph.Graph.packages:type_name -> graph.Package
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_graph_proto_init() }
func file_proto_graph_proto_init() {
	if File_proto_graph_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_graph_proto_rawDesc), len(file_proto_graph_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_graph_proto_goTypes,
		DependencyIndexes: file_proto_graph_proto_depIdxs,
		EnumInfos:         file_proto_graph_proto_enumTypes,
		MessageInfos:      file_proto_graph_proto_msgTypes,
	}.Build()
	File_proto_graph_proto = out.File
	file_proto_graph_proto_goTypes = nil
	file_proto_graph_proto_depIdxs = nil
}
